URL_PATH = 'https://www.olx.ua/transport/legkovye-avtomobili/?search%5Bfilter_float_price%3Afrom%5D=1500000'

ITEMS_LINKS_CSS = '.link.linkWithHash'
SHOW_PHONE_NUMBER_CSS = 'span.spoiler'
PHONE_NUMBER_VISIBLE = 'display: none;'
PHONE_NUMBER_CSS = 'strong.xx-large'
USER_NAME_CSS = '.offer-user__details a'
PRICE_CSS = '.price-label strong'
USER_SINCE_CLASS = 'user-since'
PAGE_LINK_CSS = '.item a'
USER_ADDRESS_CSS = 'address p'